### ISSUE TITLE
Build scripts

### ISSUE THREAD

**Issue by TechnologyClassroom** [Raizo62/LiveRaizo#1]
Where is the source for building LiveRaizo images?

**Comment by Raizo62** [comment]
Hi

I don't share the LiveRaizo code yet, because it's dirty; there are some manual actions that are hard to explain in a doc and it also contains some private configuration

**Comment by TechnologyClassroom** [comment]
"Perfection is the enemy of good."

You should post what you have even if the doc is incomplete.  Use a linter before posting if it really bothers you.

With distributions, building trust is important.  An unknown build process could add malicious functionality intentionally or unintentionally.

**Comment by Raizo62** [comment]
It takes a lot of work to migrate it to github (to remove the configurations of the private version, explain the manual actions,...).

I'll do it when I have enough issues or updates and it's easier to integrate them through github....
